version: "3.8"

services:
  db:
    image: postgres:16
    container_name: odoo19-db
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  odoo:
    build:
      context: ./odoo
      dockerfile: Dockerfile
      args:
        WKHTML_VERSION: "0.12.6.1-3"
    image: odoo19-wkhtml:latest
    container_name: odoo19
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
    command: ["/usr/bin/odoo", "-c", "/etc/odoo/odoo.conf"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8069/web/login > /dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  db-data:
